export const zh = {
  entry: '记忆', addLesson: '新增经验', selectWork: '选择工作经历', selectProject: '选择项目', content: '内容', resumeView: '简历', directory: '目录', view: '视图', sort: '排序', createdAt: '创建时间', newest: '最新在前', oldest: '最早在前', addWork: '新增工作经历', addProject: '新增项目', path: '路径', viewProjects: '查看项目', resume: '职业履历', personal: '个人信息与能力', work: '工作经历', project: '项目经历', lesson: '经验',
  name: '姓名', position: '职业定位', specialties: '擅长领域', abilities: '能力项', title: '名称', startDate: '开始日期', endDate: '截至日期', present: '至今', experienceTime: '经历时间', organization: '公司', jobTitle: '岗位', highlights: '主要事迹', role: '承担角色', workId: '所属工作经历', parentId: '所属项目',
  edit: '编辑', add: '新增', save: '保存', cancel: '取消', close: '关闭', lessons: '查看经验', history: '版本历史', refresh: '刷新', export: '导出', import: '导入', remove: '移除', restore: '恢复此版本', back: '返回',
  emptyWork: '暂无工作经历', emptyProject: '暂无项目经历', emptyLessons: '暂无经验', emptyHistory: '暂无版本',
  agentTools: '允许Agent使用', revision: '版本', human: '人工', agent: 'Agent', before: '修改前', after: '修改后', none: '未填写', noWork: '独立项目',
  clear: '清空记忆', confirmClear: '确认清空', clearTitle: '清空全部记忆？', clearHint: '全部履历、经验和版本历史将被删除，无法恢复。Agent 使用开关保持不变。', removeTitle: '移除这条记录？', removeHint: '当前履历将移除此条目，版本历史仍然保留。有下级条目时，请先移除或更改关联。', restoreTitle: '恢复整个履历到此版本？', restoreHint: '将覆盖当前履历，并创建新版本。', importTitle: '导入并替换当前履历？', importHint: '文件中的履历将成为新版本，原有版本历史保留。', confirm: '确认', loading: '正在读取履历…', deleteSummary: '移除履历条目', restoreSummary: '恢复历史履历', importSummary: '导入履历',
  'error.date': '请选择有效日期。', 'error.dateRange': '截至日期不能早于开始日期。', 'error.conflict': '内容已更新。你的编辑仍保留，请关闭编辑、刷新后重新修改。', 'error.protected': '此操作仅支持在界面中执行。', 'error.busy': '记忆正在写入，请稍后重试。', 'error.invalid': '内容格式无效，请检查字段或导入文件。', 'error.content': '请填写必要内容：工作经历至少一项、项目名称或经验正文。', 'error.reference': '所属条目不存在，或仍有其他条目引用此条目。', 'error.missing': '此版本不存在。', 'error.disabled': 'Agent 工具已关闭。', 'error.storage': '无法读取或保存记忆，请检查文件权限与宿主日志。', 'error.forbidden': '会话已失效，请重新打开应用。', 'error.unavailable': '记忆服务暂不可用。', 'error.generic': '操作失败，请刷新后重试。',
} as const
export type Key = keyof typeof zh
export const en: Record<Key, string> = {
  entry: 'Memory', addLesson: 'Add lesson', selectWork: 'Select work experience', selectProject: 'Select a project', content: 'Content', resumeView: 'Resume', directory: 'Directory', view: 'View', sort: 'Sort', createdAt: 'Created', newest: 'Newest first', oldest: 'Oldest first', addWork: 'Add work experience', addProject: 'Add project', path: 'Path', viewProjects: 'View projects', resume: 'Career record', personal: 'Profile & capabilities', work: 'Work experience', project: 'Projects', lesson: 'Lesson',
  name: 'Name', position: 'Professional focus', specialties: 'Specialties', abilities: 'Capabilities', title: 'Title', startDate: 'Start date', endDate: 'End date', present: 'Present', experienceTime: 'Experience date', organization: 'Company', jobTitle: 'Position', highlights: 'Highlights', role: 'Role', workId: 'Work experience', parentId: 'Project',
  edit: 'Edit', add: 'Add', save: 'Save', cancel: 'Cancel', close: 'Close', lessons: 'View lessons', history: 'Version history', refresh: 'Refresh', export: 'Export', import: 'Import', remove: 'Remove', restore: 'Restore this version', back: 'Back',
  emptyWork: 'No work experience', emptyProject: 'No projects', emptyLessons: 'No lessons', emptyHistory: 'No revisions',
  agentTools: 'Allow Agent access', revision: 'Revision', human: 'Human', agent: 'Agent', before: 'Before', after: 'After', none: 'Not provided', noWork: 'Independent project',
  clear: 'Clear memory', confirmClear: 'Confirm clear', clearTitle: 'Clear all memory?', clearHint: 'Deletes all resume content, lessons and revision history. This cannot be undone. The Agent tool setting stays unchanged.', removeTitle: 'Remove this record?', removeHint: 'This entry will leave the current resume. Version history remains. Remove or reassign its children first.', restoreTitle: 'Restore the entire resume to this revision?', restoreHint: 'Replaces the current resume, creating a new revision.', importTitle: 'Import and replace the current resume?', importHint: 'The imported resume becomes a new revision. Existing history remains.', confirm: 'Confirm', loading: 'Loading career record…', deleteSummary: 'Remove career entry', restoreSummary: 'Restore career revision', importSummary: 'Import career record',
  'error.date': 'Select a valid date.', 'error.dateRange': 'End date cannot precede start date.', 'error.conflict': 'The record changed. Your draft is preserved. Close the editor, refresh and edit again.', 'error.protected': 'This operation is only available in the user interface.', 'error.busy': 'Memory is being written. Try again shortly.', 'error.invalid': 'Invalid content. Check the fields or import file.', 'error.content': 'Required content is missing: any work field, a project title or the lesson text.', 'error.reference': 'The parent entry is missing, or another entry still references this one.', 'error.missing': 'Revision not found.', 'error.disabled': 'Agent tools are disabled.', 'error.storage': 'Cannot read or save memory. Check file permissions and host logs.', 'error.forbidden': 'Your session expired. Reopen the application.', 'error.unavailable': 'Memory service is unavailable.', 'error.generic': 'Operation failed. Refresh and try again.',
}
let runtime: ((key: string) => string) | undefined
export function setTranslate(t: (key: string) => string): void { runtime = t }
export function t(key: Key): string {
  const value = runtime?.(key)
  if (value && value !== key) return value
  return (typeof document !== 'undefined' && document.documentElement.lang.startsWith('en') ? en : zh)[key]
}
