export const zh = {
  entry: '记忆', addArchive: '新增档案', selectWork: '选择工作经历', selectProject: '选择项目', content: '内容', legacyArchives: '工作档案', resumeView: '简历', directory: '目录', view: '视图', sort: '排序', createdAt: '创建时间', newest: '最新在前', oldest: '最早在前', expand: '展开', collapse: '收起', unknownDate: '时间未知', addWork: '新增工作经历', addProject: '新增项目', path: '路径', viewProjects: '查看项目', resume: '职业履历', personal: '个人信息与能力', work: '工作经历', project: '项目经历', episode: '经历档案',
  name: '姓名', position: '职业定位', specialties: '擅长领域', abilities: '能力项', title: '名称', period: '时间', organization: '公司', jobTitle: '岗位', highlights: '主要事迹', role: '承担角色', responsibilities: '岗位职责', achievements: '成绩与效果', objective: '项目目标', contribution: '主要工作', outcome: '项目成果', workId: '所属工作经历', parentId: '关联经历', context: '背景与约束', actions: '实际行动', result: '观察结果', evidence: '证据与来源', lesson: '可复用经验', limits: '适用边界',
  edit: '编辑', add: '新增', save: '保存', cancel: '取消', close: '关闭', archives: '查看档案', history: '版本历史', refresh: '刷新', export: '导出', import: '导入', remove: '移除', restore: '恢复此版本', back: '返回',
  emptyWork: '暂无工作经历', emptyProject: '暂无项目经历', emptyArchives: '暂无档案', emptyHistory: '暂无版本',
  agentTools: '允许 Agent 使用工具', protected: '人工确认', unlock: '允许 Agent 修改', revision: '版本', human: '人工', agent: 'Agent', before: '修改前', after: '修改后', none: '未填写', noWork: '独立项目',
  clear: '清空记忆', confirmClear: '确认清空', clearTitle: '清空全部记忆？', clearHint: '全部履历、档案和版本历史将被删除，无法恢复。Agent 工具开关保持不变。', removeTitle: '移除这条经历？', removeHint: '当前履历将移除此条目，版本历史仍然保留。有关联档案时，请先移除或更改关联。', restoreTitle: '恢复整个履历到此版本？', restoreHint: '将覆盖当前履历，并创建新版本。恢复的字段标记为人工确认。', importTitle: '导入并替换当前履历？', importHint: '文件中的履历将成为新版本，原有版本历史保留。导入字段标记为人工确认。', confirm: '确认', loading: '正在读取履历…', deleteSummary: '移除履历条目', restoreSummary: '恢复历史履历', importSummary: '导入履历',
  'error.conflict': '内容已更新。你的编辑仍保留，请关闭编辑、刷新后重新修改。', 'error.protected': '该字段已经人工确认，Agent 无法覆盖。', 'error.busy': '记忆正在写入，请稍后重试。', 'error.invalid': '内容格式无效，请检查字段或导入文件。', 'error.title': '请填写经历内容。', 'error.reference': '关联经历不存在，或仍有其他条目引用此经历。', 'error.evidence': '请补充档案的证据与来源。', 'error.capacity': '版本存储已达容量上限，请先导出备份。', 'error.missing': '此版本不存在。', 'error.disabled': 'Agent 工具已关闭。', 'error.storage': '无法读取或保存记忆，请检查文件权限与宿主日志。', 'error.forbidden': '会话已失效，请重新打开应用。', 'error.unavailable': '记忆服务暂不可用。', 'error.generic': '操作失败，请刷新后重试。',
} as const
export type Key = keyof typeof zh
export const en: Record<Key, string> = {
  entry: 'Memory', addArchive: 'Add archive', selectWork: 'Select work experience', selectProject: 'Select a project', content: 'Content', legacyArchives: 'Work archives', resumeView: 'Resume', directory: 'Directory', view: 'View', sort: 'Sort', createdAt: 'Created', newest: 'Newest first', oldest: 'Oldest first', expand: 'Expand', collapse: 'Collapse', unknownDate: 'Unknown date', addWork: 'Add work experience', addProject: 'Add project', path: 'Path', viewProjects: 'View projects', resume: 'Career record', personal: 'Profile & capabilities', work: 'Work experience', project: 'Projects', episode: 'Experience archive',
  name: 'Name', position: 'Professional focus', specialties: 'Specialties', abilities: 'Capabilities', title: 'Title', period: 'Period', organization: 'Company', jobTitle: 'Position', highlights: 'Highlights', role: 'Role', responsibilities: 'Responsibilities', achievements: 'Achievements & impact', objective: 'Objective', contribution: 'Contribution', outcome: 'Outcome', workId: 'Work experience', parentId: 'Related experience', context: 'Context & constraints', actions: 'Actions taken', result: 'Observed result', evidence: 'Evidence & sources', lesson: 'Reusable lesson', limits: 'Applicability & limits',
  edit: 'Edit', add: 'Add', save: 'Save', cancel: 'Cancel', close: 'Close', archives: 'View archives', history: 'Version history', refresh: 'Refresh', export: 'Export', import: 'Import', remove: 'Remove', restore: 'Restore this version', back: 'Back',
  emptyWork: 'No work experience', emptyProject: 'No projects', emptyArchives: 'No archives', emptyHistory: 'No revisions',
  agentTools: 'Allow Agent tools', protected: 'Human-confirmed', unlock: 'Allow Agent edits', revision: 'Revision', human: 'Human', agent: 'Agent', before: 'Before', after: 'After', none: 'Not provided', noWork: 'Independent project',
  clear: 'Clear memory', confirmClear: 'Confirm clear', clearTitle: 'Clear all memory?', clearHint: 'Deletes all resume content, archives and revision history. This cannot be undone. The Agent tool setting stays unchanged.', removeTitle: 'Remove this experience?', removeHint: 'This entry will leave the current resume. Version history remains. Remove or reassign related archives first.', restoreTitle: 'Restore the entire resume to this revision?', restoreHint: 'Replaces the current resume, creating a new revision. Restored fields become human-confirmed.', importTitle: 'Import and replace the current resume?', importHint: 'The imported resume becomes a new revision. Existing history remains. Imported fields become human-confirmed.', confirm: 'Confirm', loading: 'Loading career record…', deleteSummary: 'Remove career entry', restoreSummary: 'Restore career revision', importSummary: 'Import career record',
  'error.conflict': 'The record changed. Your draft is preserved. Close the editor, refresh and edit again.', 'error.protected': 'This field is human-confirmed and cannot be overwritten by the Agent.', 'error.busy': 'Memory is being written. Try again shortly.', 'error.invalid': 'Invalid content. Check the fields or import file.', 'error.title': 'Experience content is required.', 'error.reference': 'The linked experience is missing, or another entry still references this one.', 'error.evidence': 'Evidence and sources are required.', 'error.capacity': 'Version storage reached its limit. Export a backup first.', 'error.missing': 'Revision not found.', 'error.disabled': 'Agent tools are disabled.', 'error.storage': 'Cannot read or save memory. Check file permissions and host logs.', 'error.forbidden': 'Your session expired. Reopen the application.', 'error.unavailable': 'Memory service is unavailable.', 'error.generic': 'Operation failed. Refresh and try again.',
}
let runtime: ((key: string) => string) | undefined
export function setTranslate(t: (key: string) => string): void { runtime = t }
export function t(key: Key): string {
  const value = runtime?.(key)
  if (value && value !== key) return value
  return (typeof document !== 'undefined' && document.documentElement.lang.startsWith('en') ? en : zh)[key]
}
